version: 2.5.1.{build}
branches:
  only:
  - feature/netcore
max_jobs: 1
configuration: Release
before_build:
- ps: >-
    nuget restore .\Programs\SweWin\SweWin.csproj -packagesDirectory .\packages\

    dotnet restore

    dotnet build .\SwissEphNet\ -c Release

build:
  verbosity: minimal
after_build:
- ps: >-
    dotnet pack .\SwissEphNet\ -c Release

    Get-ChildItem . -Recurse -Include "*.symbols.nupkg" | Delete-Item

    .\make-dist.ps1

test_script:
- cmd: dotnet test .\Tests\SwissEphNet.Tests\
artifacts:
- path: SwissEphNet/bin/$(configuration)/*.nupkg
  name: Nuget
- path: binaries
  name: Binary
deploy:
- provider: Environment
  name: Nuget
