//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18444
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SwephNet.Locales {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LSR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LSR() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SwephNet.Locales.LSR", typeof(LSR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {0}: not found.
        /// </summary>
        public static string Asteroid_NameNotFound {
            get {
                return ResourceManager.GetString("Asteroid_NameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t find a constructor for type &apos;{0}&apos;.
        /// </summary>
        public static string Dependency_Error_CantFindConstructor {
            get {
                return ResourceManager.GetString("Dependency_Error_CantFindConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &apos;{0}&apos; can&apos;t be instanciate.
        /// </summary>
        public static string Dependency_Error_CantInstanciateType {
            get {
                return ResourceManager.GetString("Dependency_Error_CantInstanciateType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t resolve parameter &apos;{0}&apos; of type &apos;{1}&apos; for construct &apos;{2}&apos;.
        /// </summary>
        public static string Dependency_Error_CantResolveParameterForConstruct {
            get {
                return ResourceManager.GetString("Dependency_Error_CantResolveParameterForConstruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Can&apos;t resolve type &apos;{0}&apos;.
        /// </summary>
        public static string Dependency_Error_CantResolveType {
            get {
                return ResourceManager.GetString("Dependency_Error_CantResolveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Error in file {0}, line {1}: {2}.
        /// </summary>
        public static string Error_ReadingFile {
            get {
                return ResourceManager.GetString("Error_ReadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à eccentricity invalid (no parabolic or hyperbolic orbits allowed).
        /// </summary>
        public static string Fictitious_ErrorEccentricityValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorEccentricityValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à elements for planet {1} not found.
        /// </summary>
        public static string Fictitious_ErrorElementsNotFound {
            get {
                return ResourceManager.GetString("Fictitious_ErrorElementsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à inclination value invalid.
        /// </summary>
        public static string Fictitious_ErrorInclinationValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorInclinationValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à invalid epoch.
        /// </summary>
        public static string Fictitious_ErrorInvalidEpoch {
            get {
                return ResourceManager.GetString("Fictitious_ErrorInvalidEpoch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à invalid equinox.
        /// </summary>
        public static string Fictitious_ErrorInvalidEquinox {
            get {
                return ResourceManager.GetString("Fictitious_ErrorInvalidEquinox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mean anomaly value invalid.
        /// </summary>
        public static string Fictitious_ErrorMeanAnomalyValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorMeanAnomalyValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à nine elements required.
        /// </summary>
        public static string Fictitious_ErrorNineElementsRequired {
            get {
                return ResourceManager.GetString("Fictitious_ErrorNineElementsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à node value invalid.
        /// </summary>
        public static string Fictitious_ErrorNodeValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorNodeValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à error no elements for fictitious body no {0}.
        /// </summary>
        public static string Fictitious_ErrorNoElements {
            get {
                return ResourceManager.GetString("Fictitious_ErrorNoElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à perihelion argument value invalid.
        /// </summary>
        public static string Fictitious_ErrorPerihelionArgumentValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorPerihelionArgumentValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à semi-axis value invalid.
        /// </summary>
        public static string Fictitious_ErrorSemiAxisValueInvalid {
            get {
                return ResourceManager.GetString("Fictitious_ErrorSemiAxisValueInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Name not found.
        /// </summary>
        public static string Fictitious_NameNotFound {
            get {
                return ResourceManager.GetString("Fictitious_NameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Adams.
        /// </summary>
        public static string FictitiousName_Adams {
            get {
                return ResourceManager.GetString("FictitiousName_Adams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Admetos.
        /// </summary>
        public static string FictitiousName_Admetos {
            get {
                return ResourceManager.GetString("FictitiousName_Admetos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Apollon.
        /// </summary>
        public static string FictitiousName_Apollon {
            get {
                return ResourceManager.GetString("FictitiousName_Apollon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cupido.
        /// </summary>
        public static string FictitiousName_Cupido {
            get {
                return ResourceManager.GetString("FictitiousName_Cupido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hades.
        /// </summary>
        public static string FictitiousName_Hades {
            get {
                return ResourceManager.GetString("FictitiousName_Hades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Harrington.
        /// </summary>
        public static string FictitiousName_Harrington {
            get {
                return ResourceManager.GetString("FictitiousName_Harrington", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Isis-Transpluto.
        /// </summary>
        public static string FictitiousName_IsisTranspluto {
            get {
                return ResourceManager.GetString("FictitiousName_IsisTranspluto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Kronos.
        /// </summary>
        public static string FictitiousName_Kronos {
            get {
                return ResourceManager.GetString("FictitiousName_Kronos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Leverrier.
        /// </summary>
        public static string FictitiousName_Leverrier {
            get {
                return ResourceManager.GetString("FictitiousName_Leverrier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lowell.
        /// </summary>
        public static string FictitiousName_Lowell {
            get {
                return ResourceManager.GetString("FictitiousName_Lowell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nibiru.
        /// </summary>
        public static string FictitiousName_Nibiru {
            get {
                return ResourceManager.GetString("FictitiousName_Nibiru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pickering.
        /// </summary>
        public static string FictitiousName_Pickering {
            get {
                return ResourceManager.GetString("FictitiousName_Pickering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Poseidon.
        /// </summary>
        public static string FictitiousName_Poseidon {
            get {
                return ResourceManager.GetString("FictitiousName_Poseidon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vulkanus.
        /// </summary>
        public static string FictitiousName_Vulkanus {
            get {
                return ResourceManager.GetString("FictitiousName_Vulkanus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zeus.
        /// </summary>
        public static string FictitiousName_Zeus {
            get {
                return ResourceManager.GetString("FictitiousName_Zeus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ceres.
        /// </summary>
        public static string PlanetName_Ceres {
            get {
                return ResourceManager.GetString("PlanetName_Ceres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Chiron.
        /// </summary>
        public static string PlanetName_Chiron {
            get {
                return ResourceManager.GetString("PlanetName_Chiron", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Earth.
        /// </summary>
        public static string PlanetName_Earth {
            get {
                return ResourceManager.GetString("PlanetName_Earth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à intp. Apogee.
        /// </summary>
        public static string PlanetName_IntpApogee {
            get {
                return ResourceManager.GetString("PlanetName_IntpApogee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à intp. Perigee.
        /// </summary>
        public static string PlanetName_IntpPerigee {
            get {
                return ResourceManager.GetString("PlanetName_IntpPerigee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Juno.
        /// </summary>
        public static string PlanetName_Juno {
            get {
                return ResourceManager.GetString("PlanetName_Juno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Jupiter.
        /// </summary>
        public static string PlanetName_Jupiter {
            get {
                return ResourceManager.GetString("PlanetName_Jupiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mars.
        /// </summary>
        public static string PlanetName_Mars {
            get {
                return ResourceManager.GetString("PlanetName_Mars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mean Apogee.
        /// </summary>
        public static string PlanetName_MeanApogee {
            get {
                return ResourceManager.GetString("PlanetName_MeanApogee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mean Node.
        /// </summary>
        public static string PlanetName_MeanNode {
            get {
                return ResourceManager.GetString("PlanetName_MeanNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mercury.
        /// </summary>
        public static string PlanetName_Mercury {
            get {
                return ResourceManager.GetString("PlanetName_Mercury", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Moon.
        /// </summary>
        public static string PlanetName_Moon {
            get {
                return ResourceManager.GetString("PlanetName_Moon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Neptune.
        /// </summary>
        public static string PlanetName_Neptune {
            get {
                return ResourceManager.GetString("PlanetName_Neptune", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à osc. Apogee.
        /// </summary>
        public static string PlanetName_OscuApogee {
            get {
                return ResourceManager.GetString("PlanetName_OscuApogee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pallas.
        /// </summary>
        public static string PlanetName_Pallas {
            get {
                return ResourceManager.GetString("PlanetName_Pallas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pholus.
        /// </summary>
        public static string PlanetName_Pholus {
            get {
                return ResourceManager.GetString("PlanetName_Pholus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Pluto.
        /// </summary>
        public static string PlanetName_Pluto {
            get {
                return ResourceManager.GetString("PlanetName_Pluto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saturn.
        /// </summary>
        public static string PlanetName_Saturn {
            get {
                return ResourceManager.GetString("PlanetName_Saturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sun.
        /// </summary>
        public static string PlanetName_Sun {
            get {
                return ResourceManager.GetString("PlanetName_Sun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à true Node.
        /// </summary>
        public static string PlanetName_TrueNode {
            get {
                return ResourceManager.GetString("PlanetName_TrueNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Uranus.
        /// </summary>
        public static string PlanetName_Uranus {
            get {
                return ResourceManager.GetString("PlanetName_Uranus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Venus.
        /// </summary>
        public static string PlanetName_Venus {
            get {
                return ResourceManager.GetString("PlanetName_Venus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Vesta.
        /// </summary>
        public static string PlanetName_Vesta {
            get {
                return ResourceManager.GetString("PlanetName_Vesta", resourceCulture);
            }
        }
    }
}
